### ISSUE TITLE
broken when viewed from https server

### ISSUE THREAD

**Issue by seangarner** [FGRibreau/doxx#5]
Because of browser restrictions the CDN content doesn't get loaded and you get an unstyled page when viewing generated files from a https server.

I've fixed in a branch 6d49c9337f72dd37f65e79c94d245ae713fe0612 but I've just realised that using protocol relative URLs means it fails when you open it as a file locally in your browser (i.e. not from a server).

I'm not sure if there's another fix that works for both file:// http:// and https://

**Comment by iwatakeshi** [comment]
*In theory*, this should be fixed in **2.1.0**. Closing issue for now.
