### ISSUE TITLE
Can't get coffeescript example to work

### ISSUE THREAD

**Issue by webteckie** [FGRibreau/doxx#50]
Does the coffee script example really work?  I've created a coffeescript file (test.coffee) with the only content being (from your README):

    ###*
     * Create an array of all the right files in the source dir
     * @param      {String}   source path
     * @param      {Object}   options
     * @param      {Function} callback
     * @jsFiddle   A jsFiddle embed URL
     * @return     {Array} an array of string path
    ###
    collectFiles = (source, options, callback) ->
        return

then ran:

node node_modules/doxx/bin/doxx --debug --title 'Test Coffeescript Doc' --source .tmp --target .tmp

I've put a sample README.md in there as well just in case.  The only thing generated is the index.html for the readme per the default template.  Any ideas what I may be doing wrong?  I'm working with the latest from master.

**Comment by jdleesmiller** [comment]
I think part of it is that [this line](https://github.com/FGRibreau/doxx/blob/9de021b8dc1271046844e264f3169268048f7fc5/lib/dir.js#L29) ignores everything in `source` that doesn't end in `js`. Changing it to something like
```
if (/\.(?:js|coffee)$/.test(file) && doNotIgnore) {
```
makes the files appear in the HTML output, but the annotations still don't seem to be parsed.

**Comment by vass-david** [comment]
Got same problem. Not grunt-doxx nor doxx works in my case. Compiled javascript code is parsed right, source coffeescript files are not parsed at all.

**Comment by japboy** [comment]
Does `dox` actually support CoffeeScript...? It doesn't seem so, and it means `mr-doc` doesn't support CoffeeScript, am I correct? I hope `mr-doc` could transpile CoffeeScript though.

**Comment by iwatakeshi** [comment]
@japboy You might be correct and I think we've might hit issue #94 . 本当にすみません。一様計画に入っていますのであちらのディカッションに参加してもらえたら嬉しいです！
@FGRibreau We'll have to start working/discussing on the blueprint of Mr. Doc's core because I' think we've hit issue #94.
