### ISSUE TITLE
TypeError 'undefined' when @return is empty

### ISSUE THREAD

**Issue by sranger** [FGRibreau/doxx#54]
I recently added some documentation to some code but did not fill in an @return value with any information, just left it blank. I had done quite a bit in my code so when I received the following error, I was quite confused; no information regrding the reason. I eventually ran doxx on each file individually by moving each into a separate directory (adding an option to the --source tag for files/folder array instead of a single directory, only, would be helpful if you're bored). Eventually, I figured out which file the error was and I had only added one function so through trial-and-error I determined it was an issue with the @return tag.
<div>
Error output:<pre>
$ doxx --source 'src/util' --target 'docs'
'doxx: [TypeError: Cannot call method 'replace' of undefined]'
$</pre>

Offending comment:
<pre>
/**
  * My comment.
  *
  * @param someValue
  * @return
  */
<pre>
</div>

**Comment by forstermatth** [comment]
This is an error thrown [here](https://github.com/FGRibreau/doxx/blob/master/lib/parser.js#L125) by the [dox](https://github.com/tj/dox) parser, and thus should be addressed in that repo. 
`nofix`

**Comment by FGRibreau** [comment]
Following @forstermatth analysis, closing this issue.
