### ISSUE TITLE
Weird return statement display + markup showing in the output.

### ISSUE THREAD

**Issue by forstermatth** [FGRibreau/doxx#58]
The return statement is missing the first and last character of the word?
![capture](https://cloud.githubusercontent.com/assets/3375444/5968097/16d00ba4-a7d1-11e4-8499-35bc591233f6.PNG)

And markup is being shown in the parameter tables:
![capture](https://cloud.githubusercontent.com/assets/3375444/5968136/7e180bcc-a7d1-11e4-9d15-68ab893f9fc9.PNG)

I only noticed this after I updated the package today.

**Comment by FGRibreau** [comment]
@forstermatth it seems like a regression, if you find why, don't hesitate to send a PR, I'll merge it :)

**Comment by forstermatth** [comment]
The return missing characters was on my side. the `return` tag requires `{type}` syntax to parse properly.
