### ISSUE TITLE
Doxx is not compatible with Windows folder structure

### ISSUE THREAD

**Issue by evertton** [FGRibreau/doxx#61]
> In the url bar i have example/docs/folder\file.js.html instead of example/docs/folder/file.js.html
> In order to make it display the comments i have to change "\" to "/" for each file for which i want to see > documentation

Complete issue in https://github.com/evertton/grunt-doxx/issues/3

**Comment by FGRibreau** [comment]
Hello @evertton, I will happily accept a PR for this (as I don't use windows), thanks :)

**Comment by evertton** [comment]
haha Certainly, I will do when have free time. :smile:
