### ISSUE TITLE
Official template - return issue

### ISSUE THREAD

**Issue by Deisss** [FGRibreau/doxx#65]
A little bug found, In the official template.jade:

Inside the 'hasParam' at the return position (line 131), there is:

td= tag.Description

while it should be:

td!= tag.description

Makes the return comment disappear, with correction, everything goes back to normal...

Don't know if it's something you wanted, but seems with this fix to correct the return comment...

**Comment by FGRibreau** [comment]
Indeed, could you please submit a PR @Deisss ? I will merge it :)
