### ISSUE TITLE
Using @description tag doubles the description

### ISSUE THREAD

**Issue by iwatakeshi** [FGRibreau/doxx#70]
It seems like for a comment like:
```javascript
   /** 
   * @public
   * @description Parses the headers for the Accept-Language.
   * @param  {object} req The request object.
   * @return {string|undefined}     The parsed Accept-Language.
   */
```
outputs in the html as:

```
Parses the headers for the Accept-Language.
Parses the headers for the Accept-Language.
```
The position of the `@description` tag does not seem to matter, it will always double the description.

Side-note: I'm currently using the gulp-doxx plugin.

**Comment by FGRibreau** [comment]
Interesting, it may indeed be a bug from doxx, you may want to start by taking a look at the default template :) 
If you find the issue, just send a PR :)

**Comment by iwatakeshi** [comment]
I won't be able to help soon but I'll try to take a look at it when I have some time.

**Comment by iwatakeshi** [comment]
@FGRibreau I took the liberty to [rewrite](https://github.com/iwatakeshi/doxx/commit/8f999b287aad9b54a6504b347d7ccddb4534d7a9) your library in ES6 this week. Of course, it will converted to ES6 using babel afterwards. 

So far the library works using babel and only a few tweaks to commander have been made but nothing major. Please let me know if this update interests you, I will be glad to contribute to make Doxx the best doc generator. 

Apart from that, I still am working on the double description bug and thought to ask what is the [`symbol.description.extra`](https://github.com/iwatakeshi/doxx/blob/master/lib/symbol.js#L101-L104) in `symbol.js` and what is the difference between [`symbol.description.full` and `symbol.description.extra`](https://github.com/FGRibreau/doxx/blob/master/views/template.jade#L133) in `template.jade`?

**Comment by FGRibreau** [comment]
@iwatakeshi that. is. AWESOME! Indeed, the code was quite old and needed a rewrite, besides the indentation that should be 2 (instead of 4) It's ok with me. you can create PR for that and I will merge it!

**Comment by iwatakeshi** [comment]
@FGRibreau  Glad you loved it! Well about the `symbol.description.extra`, it doesn't seem to do much but cause the bug. 

The bug doesn't occur when `symbol.description.extra` line is removed in the jade template. We can keep the `symbol.description.extra` in the code just in case an issue is reported and just remove it from the template which I have already done in the fork (I'll probably comment it in the code about it that we don't have a clue what its for haha).
