### ISSUE TITLE
docs / gh-pages

### ISSUE THREAD

**Issue by cliftonc** [FGRibreau/doxx#86]
I think we should separate the docs out into the gh-pages branch, and have a new build script that generates a version of the docs in all of the available themes (with a landing page) - so you don't see docs commits on api changes in the core.

I'll submit a PR to show how it can work.

**Comment by iwatakeshi** [comment]
:+1: I wouldn't mind. @FGRibreau any thoughts?

**Comment by FGRibreau** [comment]
@cliftonc @iwatakeshi great idea! :+1:

**Comment by iwatakeshi** [comment]
Closing issue, I've just merged it ;)
